name: Lint and Format Python Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install autopep8 pylint flake8

    - name: Run autopep8
      run: |
        autopep8 --in-place --aggressive --aggressive hw2_debugging.py rand.py

    - name: Run pylint
      run: |
        pylint hw2_debugging.py rand.py

    - name: Run flake8
      run: |
        flake8 hw2_debugging.py rand.py
