# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Radon

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up radon
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade radon
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run radon
      run: |
        echo "Cyclomatic complexity:"
        radon cc ./hw2/ || true
        echo "Halstead metrics:"
        radon hal ./hw2/ || true
        echo "Maintainability index:"
        radon mi ./hw2/ || true
        echo "Raw figures"
        radon raw ./hw2/ || true
